%%{init: {"theme": "neutral"}}%%
flowchart TD
    U1["U1<br/>NE555"]
    U2["U2<br/>CD4017"]
    D1["D1<br/>red LED"]
    D2["D2<br/>red LED"]
    D3["D3<br/>red LED"]
    D4["D4<br/>red LED"]
    D5["D5<br/>red LED"]
    D6["D6<br/>red LED"]
    D7["D7<br/>red LED"]
    D8["D8<br/>red LED"]
    D9["D9<br/>red LED"]
    D10["D10<br/>red LED"]
    R1["R1<br/>470Ω"]
    R2["R2<br/>470Ω"]
    R3["R3<br/>470Ω"]
    R4["R4<br/>470Ω"]
    R5["R5<br/>470Ω"]
    R6["R6<br/>470Ω"]
    R7["R7<br/>470Ω"]
    R8["R8<br/>470Ω"]
    R9["R9<br/>470Ω"]
    R10["R10<br/>470Ω"]
    R11["R11<br/>47000Ω"]
    R12["R12<br/>4700Ω"]
    C1["C1<br/>1e-07F"]
    C2["C2<br/>1e-08F"]
    R13["R13<br/>10000Ω"]
    vcc(("vcc"))
    net_21(("net_21"))
    net_11(("net_11"))
    net_12(("net_12"))
    net_1(("net_1"))
    net_20(("net_20"))
    net_10(("net_10"))
    net_19(("net_19"))
    net_9(("net_9"))
    net_18(("net_18"))
    net_8(("net_8"))
    net_17(("net_17"))
    net_7(("net_7"))
    net_16(("net_16"))
    net_6(("net_6"))
    net_15(("net_15"))
    net_5(("net_5"))
    net_14(("net_14"))
    net_4(("net_4"))
    net_13(("net_13"))
    net_3(("net_3"))
    gnd(("gnd"))
    C1 ---|"t1"| vcc
    C1 ---|"t2"| vcc
    C2 ---|"t1"| vcc
    C2 ---|"t2"| vcc
    D1 ---|"anode"| net_21
    D1 ---|"cathode"| net_11
    D10 ---|"anode"| net_12
    D10 ---|"cathode"| net_1
    D2 ---|"anode"| net_20
    D2 ---|"cathode"| net_10
    D3 ---|"anode"| net_19
    D3 ---|"cathode"| net_9
    D4 ---|"anode"| net_18
    D4 ---|"cathode"| net_8
    D5 ---|"anode"| net_17
    D5 ---|"cathode"| net_7
    D6 ---|"anode"| net_16
    D6 ---|"cathode"| net_6
    D7 ---|"anode"| net_15
    D7 ---|"cathode"| net_5
    D8 ---|"anode"| net_14
    D8 ---|"cathode"| net_4
    D9 ---|"anode"| net_13
    D9 ---|"cathode"| net_3
    R1 ---|"t1"| net_11
    R1 ---|"t2"| gnd
    R10 ---|"t1"| net_1
    R10 ---|"t2"| gnd
    R11 ---|"t1"| vcc
    R11 ---|"t2"| vcc
    R12 ---|"t1"| vcc
    R12 ---|"t2"| vcc
    R13 ---|"t1"| vcc
    R13 ---|"t2"| vcc
    R2 ---|"t1"| net_10
    R2 ---|"t2"| gnd
    R3 ---|"t1"| net_9
    R3 ---|"t2"| gnd
    R4 ---|"t1"| net_8
    R4 ---|"t2"| gnd
    R5 ---|"t1"| net_7
    R5 ---|"t2"| gnd
    R6 ---|"t1"| net_6
    R6 ---|"t2"| gnd
    R7 ---|"t1"| net_5
    R7 ---|"t2"| gnd
    R8 ---|"t1"| net_4
    R8 ---|"t2"| gnd
    R9 ---|"t1"| net_3
    R9 ---|"t2"| gnd
    U1 ---|"GND"| gnd
    U1 ---|"RESET"| vcc
    U1 ---|"VCC"| vcc
    U2 ---|"Q0"| net_21
    U2 ---|"Q1"| net_20
    U2 ---|"Q2"| net_19
    U2 ---|"Q3"| net_18
    U2 ---|"Q4"| net_17
    U2 ---|"Q5"| net_16
    U2 ---|"Q6"| net_15
    U2 ---|"Q7"| net_14
    U2 ---|"Q8"| net_13
    U2 ---|"Q9"| net_12
    U2 ---|"VDD"| vcc
    U2 ---|"VSS"| gnd
