%%{init: {"theme": "neutral"}}%%
flowchart TD
    U1["U1<br/>NE555"]
    U2["U2<br/>NE555"]
    R1["R1<br/>47000Ω"]
    R2["R2<br/>47000Ω"]
    C1["C1<br/>2.2e-06F"]
    C2["C2<br/>1e-08F"]
    R3["R3<br/>4700Ω"]
    R4["R4<br/>4700Ω"]
    C3["C3<br/>1e-07F"]
    C4["C4<br/>1e-08F"]
    R5["R5<br/>100Ω"]
    C5["C5<br/>1e-05F"]
    LS1["LS1<br/>8Ω spkr"]
    net_9(("net_9"))
    gnd(("gnd"))
    net_8(("net_8"))
    net_5(("net_5"))
    net_4(("net_4"))
    net_2(("net_2"))
    net_0(("net_0"))
    vcc(("vcc"))
    net_10(("net_10"))
    net_6(("net_6"))
    net_3(("net_3"))
    net_11(("net_11"))
    C1 ---|"t1"| net_9
    C1 ---|"t2"| gnd
    C2 ---|"t1"| net_8
    C2 ---|"t2"| gnd
    C3 ---|"t1"| net_5
    C3 ---|"t2"| gnd
    C4 ---|"t1"| net_4
    C4 ---|"t2"| gnd
    C5 ---|"t1"| net_2
    C5 ---|"t2"| net_0
    LS1 ---|"t1"| net_0
    LS1 ---|"t2"| gnd
    R1 ---|"t1"| vcc
    R1 ---|"t2"| net_10
    R2 ---|"t1"| net_10
    R2 ---|"t2"| net_9
    R3 ---|"t1"| vcc
    R3 ---|"t2"| net_6
    R4 ---|"t1"| net_6
    R4 ---|"t2"| net_5
    R5 ---|"t1"| net_3
    R5 ---|"t2"| net_2
    U1 ---|"CONT"| net_8
    U1 ---|"DISCH"| net_10
    U1 ---|"GND"| gnd
    U1 ---|"OUT"| net_11
    U1 ---|"RESET"| vcc
    U1 ---|"THRES"| net_9
    U1 ---|"TRIG"| net_9
    U1 ---|"VCC"| vcc
    U2 ---|"CONT"| net_4
    U2 ---|"DISCH"| net_6
    U2 ---|"GND"| gnd
    U2 ---|"OUT"| net_3
    U2 ---|"RESET"| net_11
    U2 ---|"THRES"| net_5
    U2 ---|"TRIG"| net_5
    U2 ---|"VCC"| vcc
