"""Render an imported netlist as Python source the user can edit.

The output is a self-contained module: imports, a `Circuit` subclass
that constructs every imported part, wires the imported nets, and an
`if __name__ == '__main__'` block that instantiates the design.  The
generated identifier names follow the same convention as the rest of
the wirebench demos — `self.<lowercased_refdes>`.

The renderer doesn't try to be clever: it iterates the
`ImportReport` produced by `import_kicad_netlist()` and emits one
line per part, one line per wire.  Users edit, extend, commit.
"""
from __future__ import annotations

from typing import Iterable

from framework.import_kicad import ImportedPart, ImportReport
from framework.import_kicad.nets import (
    NetRecord, looks_like_high_rail, looks_like_low_rail, resolve_port,
)
from framework.import_kicad.resolver import KiCadComponent
from framework.part import Part


def emit(
    report: ImportReport,
    *,
    class_name: str = 'ImportedDesign',
    source_path: str | None = None,
) -> str:
    """Render Python source.  The output is one string, ready to be
    written to disk."""
    lines: list[str] = []
    lines.append('"""Generated by `wirebench import-kicad`.')
    if source_path:
        lines.append('')
        lines.append(f"Source: {source_path}")
    lines.append('')
    lines.append("Edit freely — the generator does not overwrite this file,")
    lines.append("so subsequent re-imports won't clobber your changes.")
    lines.append('"""')
    lines.append('from __future__ import annotations')
    lines.append('')
    lines.extend(_imports_for(report))
    lines.append('')
    lines.append('')
    lines.append(f"class {class_name}(Circuit):")
    lines.append('    def __init__(self) -> None:')
    _emit_part_instantiations(lines, report)
    _emit_wires(lines, report)
    lines.append('        super().__init__()')
    lines.append('')
    lines.append('')
    lines.append("if __name__ == '__main__':")
    lines.append(f"    design = {class_name}()")
    lines.append('    print(f"Constructed {type(design).__name__} with "')
    lines.append('          f"{len(design.parts)} parts.")')
    lines.append('')
    return '\n'.join(lines)


def _imports_for(report: ImportReport) -> list[str]:
    class_names = sorted({p.klass.__name__ for p in report.parts})
    needs_rail = _any_rail_needed(report)
    if needs_rail and 'Rail' not in class_names:
        class_names.append('Rail')
    class_names.sort()

    imports = [
        'from wirebench import Circuit, wire',
    ]
    # Distinguish framework-catalogue imports from synthesised
    # UnknownPart placeholders.  Catalogue parts come from the
    # `wirebench` top-level (re-exported there for the demo API).
    # Synthesised UnknownPart classes live only in the import session
    # — for the generated file we emit an explanatory comment and
    # a `# TODO: replace UnknownPart with a real wirebench class`.
    catalogue: list[str] = []
    placeholders: list[str] = []
    for p in report.parts:
        name = p.klass.__name__
        if p.is_unknown_placeholder:
            placeholders.append(name)
        else:
            catalogue.append(name)
    catalogue = sorted(set(catalogue))
    placeholders = sorted(set(placeholders))

    if needs_rail and 'Rail' not in catalogue:
        catalogue.append('Rail')
        catalogue.sort()

    if catalogue:
        imports.append(f"from wirebench import {', '.join(catalogue)}")

    if placeholders:
        imports.append('')
        imports.append('# UnknownPart placeholders — the importer could not')
        imports.append('# resolve these to a wirebench catalogue class.')
        imports.append("# Replace with the real class once it's added; the")
        imports.append('# generated file imports the placeholder factory so')
        imports.append('# the design constructs while you investigate.')
        imports.append(
            'from framework.import_kicad.unknown_part import '
            'make_unknown_part_class'
        )

    return imports


def _emit_part_instantiations(lines: list[str], report: ImportReport) -> None:
    if not report.parts:
        return
    for p in report.parts:
        attr = _attr_for(p.refdes)
        rd_number = _refdes_number(p.refdes)
        ctor = _constructor_for(p, rd_number)
        lines.append(f"        self.{attr} = {ctor}")


def _emit_wires(lines: list[str], report: ImportReport) -> None:
    """Emit `wire()` calls reconstructing each net.  Power / ground
    nets get a synthesised Rail; mixed-signal rails are split per
    signal_type so the wire() invariants don't fire."""
    refdes_to_part_kind: dict[str, str] = {
        p.refdes: p.klass.__name__ for p in report.parts
    }
    high_rail_emitted: set[str] = set()
    low_rail_emitted:  set[str] = set()
    rail_counter = [0]

    def rail_attr(prefix: str, signal: str) -> str:
        rail_counter[0] += 1
        return f"{prefix.lower()}_{signal.lower()}_rail"

    for net in report.nets:
        if not net.nodes:
            continue
        is_high = looks_like_high_rail(net.name)
        is_low  = looks_like_low_rail(net.name)
        nodes_text = [
            _port_expr(refdes_to_part_kind.get(ref, ''), ref, pin)
            for ref, pin in net.nodes
        ]
        # Drop unresolved entries (where _port_expr returns None).
        port_lines = [t for t in nodes_text if t is not None]
        if is_high or is_low:
            kind = 'vcc' if is_high else 'gnd'
            attr = f"{kind}"
            already = high_rail_emitted if is_high else low_rail_emitted
            if attr not in already:
                level = 'True' if is_high else 'False'
                lines.append(
                    f"        self.{attr} = Rail({level})"
                )
                already.add(attr)
            if port_lines:
                lines.append(
                    f"        wire(self.{attr}.ports['out'], "
                    f"{', '.join(port_lines)})"
                )
        else:
            if len(port_lines) < 2:
                continue
            lines.append(f"        wire({', '.join(port_lines)})")


def _port_expr(class_name: str, refdes: str, pin_number: int) -> str | None:
    """Produce the `self.<attr>.ports['<name>']` expression for a
    given netlist node.  Maps pin numbers to known port names for
    well-known passive shapes; falls back to a numbered lookup for
    chips."""
    attr = _attr_for(refdes)
    if class_name in ('Resistor', 'Capacitor', 'Inductor'):
        port = 't1' if pin_number == 1 else 't2'
        return f"self.{attr}.ports['{port}']"
    if class_name == 'LED':
        port = 'anode' if pin_number == 1 else 'cathode'
        return f"self.{attr}.ports['{port}']"
    if class_name.startswith('D'):
        port = 'anode' if pin_number == 1 else 'cathode'
        return f"self.{attr}.ports['{port}']"
    # Chip / connector: use ports_by_number at runtime.
    return f"self.{attr}.ports_by_number[{pin_number}]"


def _attr_for(refdes: str) -> str:
    return refdes.lower()


def _refdes_number(refdes: str) -> int:
    digits = ''.join(c for c in refdes if c.isdigit())
    return int(digits) if digits else 1


def _constructor_for(p: ImportedPart, rd_number: int) -> str:
    name = p.klass.__name__
    if name == 'Resistor':
        return f"Resistor(ohms={_guess_value(p, fallback=330)!r}, refdes_number={rd_number})"
    if name == 'Capacitor':
        return f"Capacitor(farads={_guess_value(p, fallback=100e-9)!r}, refdes_number={rd_number})"
    if name == 'Inductor':
        return f"Inductor(henries={_guess_value(p, fallback=100e-6)!r}, refdes_number={rd_number})"
    if name == 'LED':
        color = p.value or 'red'
        return f"LED(color={color!r}, refdes_number={rd_number})"
    if name == 'Cell':
        return f"Cell(initial_state_of_charge=1.0, refdes_number={rd_number})"
    if p.is_unknown_placeholder:
        return (
            f"make_unknown_part_class({name!r}, [])(refdes_number={rd_number})"
        )
    return f"{name}(refdes_number={rd_number})"


def _guess_value(p: ImportedPart, *, fallback: float) -> float:
    try:
        return float(p.value)
    except (TypeError, ValueError):
        return fallback


def _any_rail_needed(report: ImportReport) -> bool:
    return any(
        looks_like_high_rail(n.name) or looks_like_low_rail(n.name)
        for n in report.nets
    )
