%%{init: {"theme": "neutral"}}%%
flowchart TD
    U1["U1<br/>ULN2003A"]
    U2["U2<br/>SN74HC04"]
    U3["U3<br/>CD4069"]
    U4["U4<br/>CD4043"]
    D1["D1<br/>red LED"]
    D2["D2<br/>green LED"]
    R1["R1<br/>10000Ω"]
    R2["R2<br/>10000Ω"]
    net_7(("net_7"))
    gnd(("gnd"))
    net_6(("net_6"))
    net_5(("net_5"))
    vcc(("vcc"))
    net_4(("net_4"))
    net_8(("net_8"))
    D1 ---|"anode"| net_7
    D1 ---|"cathode"| gnd
    D2 ---|"anode"| net_6
    D2 ---|"cathode"| gnd
    R1 ---|"t1"| net_5
    R1 ---|"t2"| vcc
    R2 ---|"t1"| net_4
    R2 ---|"t2"| vcc
    U1 ---|"GND"| gnd
    U1 ---|"out_1"| net_5
    U1 ---|"out_2"| net_4
    U2 ---|"GND"| gnd
    U2 ---|"VCC"| vcc
    U2 ---|"a_1"| net_4
    U2 ---|"a_2"| gnd
    U2 ---|"a_3"| gnd
    U2 ---|"a_4"| gnd
    U2 ---|"a_5"| gnd
    U2 ---|"a_6"| gnd
    U2 ---|"y_1"| net_8
    U3 ---|"VDD"| vcc
    U3 ---|"VSS"| gnd
    U3 ---|"a_1"| net_7
    U3 ---|"a_2"| gnd
    U3 ---|"a_3"| gnd
    U3 ---|"a_4"| gnd
    U3 ---|"a_5"| gnd
    U3 ---|"a_6"| gnd
    U3 ---|"y_1"| net_6
    U4 ---|"VDD"| vcc
    U4 ---|"VSS"| gnd
    U4 ---|"oe"| vcc
    U4 ---|"q_1"| net_7
    U4 ---|"r_1"| net_8
    U4 ---|"r_2"| gnd
    U4 ---|"r_3"| gnd
    U4 ---|"r_4"| gnd
    U4 ---|"s_1"| net_5
    U4 ---|"s_2"| gnd
    U4 ---|"s_3"| gnd
    U4 ---|"s_4"| gnd
