%%{init: {"theme": "neutral"}}%%
flowchart TD
    subgraph A1["A1: Power Source Rev A"]
    end
    subgraph A2["A2: Fan Cooling Module Rev A"]
        U1["U1<br/>TMP302"]
        U2["U2<br/>SN74AHC1G14"]
        Q1["Q1<br/>Q2N7000"]
        D1["D1<br/>D1N4728A"]
        R1["R1<br/>10000Ω"]
        R2["R2<br/>10000Ω"]
        R3["R3<br/>10000Ω"]
    end
    net_6(("net_6"))
    net_5(("net_5"))
    net_4(("net_4"))
    net_3(("net_3"))
    D1 ---|"anode"| net_6
    D1 ---|"cathode"| net_6
    R1 ---|"t1"| net_5
    R1 ---|"t2"| net_5
    R2 ---|"t1"| net_4
    R2 ---|"t2"| net_4
    R3 ---|"t1"| net_3
    R3 ---|"t2"| net_3
