%%{init: {"theme": "neutral"}}%%
flowchart TD
    U1["U1<br/>TPS2660"]
    U2["U2<br/>LM5002"]
    U3["U3<br/>LM5160"]
    L1["L1<br/>3.3e-05H"]
    D1["D1<br/>D1N5817"]
    C10["C10<br/>0.0012F"]
    C1["C1<br/>1e-08F"]
    C2["C2<br/>1e-06F"]
    C3["C3<br/>1e-06F"]
    C4["C4<br/>3.3e-09F"]
    C5["C5<br/>2.2e-08F"]
    C6["C6<br/>1e-06F"]
    C7["C7<br/>1e-07F"]
    C8["C8<br/>1e-06F"]
    C9["C9<br/>1e-07F"]
    C12["C12<br/>1e-06F"]
    C13["C13<br/>0.00022F"]
    C14["C14<br/>1e-06F"]
    C15["C15<br/>2.2e-06F"]
    R6["R6<br/>715000Ω"]
    R7["R7<br/>226000Ω"]
    R11["R11<br/>40200Ω"]
    R16["R16<br/>10000Ω"]
    vcc(("vcc"))
    C1 ---|"t1"| vcc
    C1 ---|"t2"| vcc
    C10 ---|"t1"| vcc
    C10 ---|"t2"| vcc
    C12 ---|"t1"| vcc
    C12 ---|"t2"| vcc
    C13 ---|"t1"| vcc
    C13 ---|"t2"| vcc
    C14 ---|"t1"| vcc
    C14 ---|"t2"| vcc
    C15 ---|"t1"| vcc
    C15 ---|"t2"| vcc
    C2 ---|"t1"| vcc
    C2 ---|"t2"| vcc
    C3 ---|"t1"| vcc
    C3 ---|"t2"| vcc
    C4 ---|"t1"| vcc
    C4 ---|"t2"| vcc
    C5 ---|"t1"| vcc
    C5 ---|"t2"| vcc
    C6 ---|"t1"| vcc
    C6 ---|"t2"| vcc
    C7 ---|"t1"| vcc
    C7 ---|"t2"| vcc
    C8 ---|"t1"| vcc
    C8 ---|"t2"| vcc
    C9 ---|"t1"| vcc
    C9 ---|"t2"| vcc
    D1 ---|"anode"| vcc
    D1 ---|"cathode"| vcc
    L1 ---|"t1"| vcc
    L1 ---|"t2"| vcc
    R11 ---|"t1"| vcc
    R11 ---|"t2"| vcc
    R16 ---|"t1"| vcc
    R16 ---|"t2"| vcc
    R6 ---|"t1"| vcc
    R6 ---|"t2"| vcc
    R7 ---|"t1"| vcc
    R7 ---|"t2"| vcc
